
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: elibrary-app
        container_name: elibrary-app
        restart: unless-stopped
        volumes:
            - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini # PHP config if needed
        networks:
            - elibrary-network
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: elibrary-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: elibrary
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
        ports:
            - "33320:3306"
        volumes:
            - elibrary-db-data:/var/lib/mysql
        networks:
            - elibrary-network

    nginx:
        image: nginx:alpine
        container_name: elibrary-nginx
        restart: unless-stopped
        ports:
            - "8909:80" # HTTP port
        volumes:
            - ./docker-compose/nginx:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - elibrary-network
            - traefik-network
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.elibrary.rule=Host(`elibrary.aicttaborachoir.co.tz`)"
            - "traefik.http.routers.elibrary.entrypoints=websecure"
            - "traefik.http.routers.elibrary.tls.certresolver=letsencrypt"
            - "traefik.http.services.elibrary.loadbalancer.server.port=80"
            - "traefik.docker.network=traefik-network"

networks:
    traefik-network:
        external: true
    elibrary-network:
        driver: bridge

volumes:
    elibrary-db-data:
